---
title: "Untitled"
author: "Mei Maddox"
date: '2022-10-27'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
options(knitr.duplicate.label = 'allow')
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, message = FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=70))
```

```{r read.previous, echo=FALSE}
source(knitr::purl("../KaggleHousePrices.Rmd", quiet = TRUE))
```

```{r libraries, include=FALSE}
library(splines)
```

```{r}
train.temp<-train %>%
  filter(!row_number() %in% c(524,692,1171,1299,1424)) %>%
  dplyr::select(-c(PoolQC, Id)) %>%
  dplyr::rename("FirstFlrSF"="1stFlrSF",
                "SecondFlrSF"="2ndFlrSF",
                "ThreeSsnPorch"="3SsnPorch")
test.new<-dplyr::select(test,-c(PoolQC, Id)) %>%
  dplyr::rename("FirstFlrSF"="1stFlrSF",
                "SecondFlrSF"="2ndFlrSF",
                "ThreeSsnPorch"="3SsnPorch")
```

```{r}
categorical <- dplyr::select(train.temp, where(is.factor)) %>% colnames()
numerical <- dplyr::select(train.temp, where(is.numeric), -SalePrice) %>% colnames()

formula <- paste0("SalePrice ~ ", paste0(categorical, collapse=' + '), " + ns(", paste0(numerical, collapse=' + '), ")")

lm.obj.init<-lm(SalePrice ~ 1,data=train.temp)
lm.obj.full<- lm(as.formula(formula),data=train.temp)

lm.fAIC.3<-MASS::stepAIC(lm.obj.init,direction=c("forward"), scope=list(upper=lm.obj.full,lower=lm.obj.init), trace=0)
lm.bAIC.3<-MASS::stepAIC(lm.obj.full,direction=c("backward"), trace=0)
```

```{r}
fAIC.3.prediction<-predict(lm.fAIC.3, newdata=test.new, interval="prediction")
bAIC.3.prediction<-predict(lm.bAIC.3, newdata=test.new, interval = "prediction")


SubmitDF <- data.frame(Id=test$Id, SalePrice=fAIC.3.prediction[,"fit"])
write.csv(file='../submissions/AIC_forward_3.csv', SubmitDF, row.names = FALSE)
SubmitDF <- data.frame(Id=test$Id, SalePrice=bAIC.3.prediction[,"fit"])
write.csv(file='../submissions/AIC_backward_3.csv', SubmitDF, row.names = FALSE)
```




